n = int(input("Digite um número:"))
print(f"Tabuada do nº{n}:")
print(f"{n}x0={n*0}\n{n}x1={n*1}\n{n}x2={n*2}\n{n}x3={n*3}\n", end="")
print(f"{n}x4-{n*4}\n{n}x5={n*5}\n{n}x6={n*6}\n{n}x7={n*7}\n{n}x8={n*8}\n", end="")
print(f"{n}x9={n*9}\n{n}x10={n*10}")